# Generated by Django 5.2.8 on 2025-11-27 06:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='was_helpful',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='dependencies',
            field=models.CharField(blank=True, help_text="Comma-separated task IDs this task depends on (e.g., '1,3,5')", max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.FloatField(help_text='Estimated hours to complete (must be > 0)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='Priority rating from 1 (low) to 10 (high)'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date', 'completed'], name='tasks_task_due_dat_803d27_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['importance'], name='tasks_task_importa_8cea0f_idx'),
        ),
    ]
